// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Fl0rencess720/Doria/src/services/tts/configs"
	"github.com/Fl0rencess720/Doria/src/services/tts/internal/biz"
	"github.com/Fl0rencess720/Doria/src/services/tts/internal/data"
	"github.com/Fl0rencess720/Doria/src/services/tts/internal/service"
)

// Injectors from wire.go:

func wireApp() *App {
	string2 := configs.GetServiceName()
	ttsRepo := data.NewTTSRepo()
	ttsUseCase := biz.NewTTSUseCase(ttsRepo)
	ttsService := service.NewTTSService(string2, ttsUseCase)
	app := NewApp(ttsService)
	return app
}

// wire.go:

type App struct {
	Server *service.TTSService
}

func NewApp(server *service.TTSService) *App {
	return &App{
		Server: server,
	}
}
