// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Fl0rencess720/Doria/src/services/image/configs"
	"github.com/Fl0rencess720/Doria/src/services/image/internal/biz"
	"github.com/Fl0rencess720/Doria/src/services/image/internal/data"
	"github.com/Fl0rencess720/Doria/src/services/image/internal/service"
)

// Injectors from wire.go:

func wireApp() *App {
	string2 := configs.GetServiceName()
	imageRepo := data.NewImageRepo()
	imageUseCase := biz.NewImageUseCase(imageRepo)
	imageService := service.NewImageService(string2, imageUseCase)
	app := NewApp(imageService)
	return app
}

// wire.go:

type App struct {
	Server *service.ImageService
}

func NewApp(server *service.ImageService) *App {
	return &App{
		Server: server,
	}
}
