// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Fl0rencess720/Bonfire-Lit/src/services/user/configs"
	"github.com/Fl0rencess720/Bonfire-Lit/src/services/user/internal/biz"
	"github.com/Fl0rencess720/Bonfire-Lit/src/services/user/internal/data"
	"github.com/Fl0rencess720/Bonfire-Lit/src/services/user/internal/service"
)

// Injectors from wire.go:

func wireApp() *App {
	string2 := configs.GetServiceName()
	db := data.NewPostgres()
	userRepository := data.NewUserRepo(db)
	userUseCase := biz.NewUserUseCase(userRepository)
	userService := service.NewUserService(string2, userUseCase)
	app := NewApp(userService)
	return app
}

// wire.go:

type App struct {
	Server *service.UserService
}

func NewApp(server *service.UserService) *App {
	return &App{
		Server: server,
	}
}
