// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: mate.proto

package mate

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// MateServiceClient is the client API for MateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MateServiceClient interface {
}

type mateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMateServiceClient(cc grpc.ClientConnInterface) MateServiceClient {
	return &mateServiceClient{cc}
}

// MateServiceServer is the server API for MateService service.
// All implementations must embed UnimplementedMateServiceServer
// for forward compatibility.
type MateServiceServer interface {
	mustEmbedUnimplementedMateServiceServer()
}

// UnimplementedMateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMateServiceServer struct{}

func (UnimplementedMateServiceServer) mustEmbedUnimplementedMateServiceServer() {}
func (UnimplementedMateServiceServer) testEmbeddedByValue()                     {}

// UnsafeMateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MateServiceServer will
// result in compilation errors.
type UnsafeMateServiceServer interface {
	mustEmbedUnimplementedMateServiceServer()
}

func RegisterMateServiceServer(s grpc.ServiceRegistrar, srv MateServiceServer) {
	// If the following call pancis, it indicates UnimplementedMateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MateService_ServiceDesc, srv)
}

// MateService_ServiceDesc is the grpc.ServiceDesc for MateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mate.MateService",
	HandlerType: (*MateServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "mate.proto",
}
