// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: mate.proto

package mate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MateService_Chat_FullMethodName                    = "/mate.MateService/Chat"
	MateService_ChatStream_FullMethodName              = "/mate.MateService/ChatStream"
	MateService_GetConversationMessages_FullMethodName = "/mate.MateService/GetConversationMessages"
	MateService_GetUserPages_FullMethodName            = "/mate.MateService/GetUserPages"
)

// MateServiceClient is the client API for MateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MateServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamResponse], error)
	GetConversationMessages(ctx context.Context, in *GetConversationMessagesRequest, opts ...grpc.CallOption) (*GetConversationMessagesResponse, error)
	GetUserPages(ctx context.Context, in *GetUserPagesRequest, opts ...grpc.CallOption) (*GetUserPagesResponse, error)
}

type mateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMateServiceClient(cc grpc.ClientConnInterface) MateServiceClient {
	return &mateServiceClient{cc}
}

func (c *mateServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, MateService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mateServiceClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MateService_ServiceDesc.Streams[0], MateService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MateService_ChatStreamClient = grpc.ServerStreamingClient[ChatStreamResponse]

func (c *mateServiceClient) GetConversationMessages(ctx context.Context, in *GetConversationMessagesRequest, opts ...grpc.CallOption) (*GetConversationMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationMessagesResponse)
	err := c.cc.Invoke(ctx, MateService_GetConversationMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mateServiceClient) GetUserPages(ctx context.Context, in *GetUserPagesRequest, opts ...grpc.CallOption) (*GetUserPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPagesResponse)
	err := c.cc.Invoke(ctx, MateService_GetUserPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MateServiceServer is the server API for MateService service.
// All implementations must embed UnimplementedMateServiceServer
// for forward compatibility.
type MateServiceServer interface {
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatStreamResponse]) error
	GetConversationMessages(context.Context, *GetConversationMessagesRequest) (*GetConversationMessagesResponse, error)
	GetUserPages(context.Context, *GetUserPagesRequest) (*GetUserPagesResponse, error)
	mustEmbedUnimplementedMateServiceServer()
}

// UnimplementedMateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMateServiceServer struct{}

func (UnimplementedMateServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedMateServiceServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedMateServiceServer) GetConversationMessages(context.Context, *GetConversationMessagesRequest) (*GetConversationMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationMessages not implemented")
}
func (UnimplementedMateServiceServer) GetUserPages(context.Context, *GetUserPagesRequest) (*GetUserPagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPages not implemented")
}
func (UnimplementedMateServiceServer) mustEmbedUnimplementedMateServiceServer() {}
func (UnimplementedMateServiceServer) testEmbeddedByValue()                     {}

// UnsafeMateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MateServiceServer will
// result in compilation errors.
type UnsafeMateServiceServer interface {
	mustEmbedUnimplementedMateServiceServer()
}

func RegisterMateServiceServer(s grpc.ServiceRegistrar, srv MateServiceServer) {
	// If the following call pancis, it indicates UnimplementedMateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MateService_ServiceDesc, srv)
}

func _MateService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MateServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MateService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MateServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MateService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MateServiceServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MateService_ChatStreamServer = grpc.ServerStreamingServer[ChatStreamResponse]

func _MateService_GetConversationMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MateServiceServer).GetConversationMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MateService_GetConversationMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MateServiceServer).GetConversationMessages(ctx, req.(*GetConversationMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MateService_GetUserPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MateServiceServer).GetUserPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MateService_GetUserPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MateServiceServer).GetUserPages(ctx, req.(*GetUserPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MateService_ServiceDesc is the grpc.ServiceDesc for MateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mate.MateService",
	HandlerType: (*MateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _MateService_Chat_Handler,
		},
		{
			MethodName: "GetConversationMessages",
			Handler:    _MateService_GetConversationMessages_Handler,
		},
		{
			MethodName: "GetUserPages",
			Handler:    _MateService_GetUserPages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _MateService_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mate.proto",
}
