// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Fl0rencess720/Doria/src/services/mate/configs"
	"github.com/Fl0rencess720/Doria/src/services/mate/internal/biz"
	"github.com/Fl0rencess720/Doria/src/services/mate/internal/data"
	"github.com/Fl0rencess720/Doria/src/services/mate/internal/service"
)

// Injectors from wire.go:

func wireApp() *App {
	string2 := configs.GetServiceName()
	db := data.NewPostgres()
	mateRepo := data.NewMateRepo(db)
	memoryServiceClient := data.NewMemoryClient()
	mateUseCase := biz.NewMateUseCase(mateRepo, memoryServiceClient)
	mateService := service.NewMateService(string2, mateUseCase)
	app := NewApp(mateService)
	return app
}

// wire.go:

type App struct {
	Server *service.MateService
}

func NewApp(server *service.MateService) *App {
	return &App{
		Server: server,
	}
}
