server:
  grpc:
    name: Doria.Service.Mate
    port: 9004
    timeout: 900s

database:
  postgres:
    dsn: host=%s user=admin password=%s dbname=bonfire_lit port=%s sslmode=disable TimeZone=Asia/Shanghai
  redis:
    db: 0
    dial_timeout: 10s
    write_timeout: 10s
    read_timeout: 10s

trace:
  otel_state: enable
  sample_ration: 1.0

pyroscope:
  state: enable

project:
  mode: dev

agent:
  model:
    chat: "Qwen/Qwen3-235B-A22B"
    retrieval: "Qwen/Qwen3-235B-A22B"

rag:
  milvus:
    username: root
  retriever:
    topK: 5
    collectionName: structured_ds1
  embedding:
    model: doubao-embedding-large-text-250515
  

