// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Fl0rencess720/Bonfire-Lit/src/gateway/internal/controllers"
	"github.com/Fl0rencess720/Bonfire-Lit/src/gateway/internal/data"
	"github.com/Fl0rencess720/Bonfire-Lit/src/gateway/service"
	"net/http"
)

// Injectors from wire.go:

func wireApp() *App {
	imageRepo := data.NewImageRepo()
	imageUsecase := controllers.NewImageUsecase(imageRepo)
	server := service.NewHTTPServer(imageUsecase)
	app := NewApp(server)
	return app
}

// wire.go:

type App struct {
	HttpServer *http.Server
}

func NewApp(server *http.Server) *App {
	return &App{
		HttpServer: server,
	}
}
