// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Fl0rencess720/Doria/src/services/chat/configs"
	"github.com/Fl0rencess720/Doria/src/services/chat/internal/biz"
	"github.com/Fl0rencess720/Doria/src/services/chat/internal/data"
	"github.com/Fl0rencess720/Doria/src/services/chat/internal/service"
)

// Injectors from wire.go:

func wireApp() *App {
	string2 := configs.GetServiceName()
	db := data.NewPostgres()
	chatRepo := data.NewChatRepo(db)
	chatUseCase := biz.NewChatUseCase(chatRepo)
	chatService := service.NewChatService(string2, chatUseCase)
	app := NewApp(chatService)
	return app
}

// wire.go:

type App struct {
	Server *service.ChatService
}

func NewApp(server *service.ChatService) *App {
	return &App{
		Server: server,
	}
}
